2025/07/04 17:30:02 [error] 19#19: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "GET /api/list-saved-notes HTTP/1.1", upstream: "http://127.0.0.1:8000/api/list-saved-notes", host: "localhost:5037", referrer: "http://localhost:5037/"
2025/07/04 17:30:02 [error] 19#19: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "GET /health HTTP/1.1", upstream: "http://127.0.0.1:8000/health", host: "localhost:5037", referrer: "http://localhost:5037/"
2025/07/04 17:30:02 [error] 19#19: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/cleanup-notes HTTP/1.1", upstream: "http://127.0.0.1:8000/api/cleanup-notes", host: "localhost:5037", referrer: "http://localhost:5037/"
2025/07/04 18:13:29 [error] 16#16: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/save-note HTTP/1.1", upstream: "http://127.0.0.1:8000/api/save-note", host: "localhost:5037", referrer: "http://localhost:5037/"
2025/07/04 18:23:00 [error] 18#18: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/save-note HTTP/1.1", upstream: "http://127.0.0.1:8000/api/save-note", host: "localhost:5037", referrer: "http://localhost:5037/"
